### ISSUE TITLE
Error when installing yireo/magento2-replace-all:2.3.4

### ISSUE THREAD

**Issue by iocampomx** [yireo/magento2-replace-all#9] opened 2020-04-30 06:26 UTC
Hi @jissereitsma, I found 2 errors with the 2.3.4 version, those are:

1. **yireo/magento2-replace-all:2.3.4** isn't published, I needed to install **yireo/magento2-replace-all:dev-magento-2.3.4**

2. When installing **yireo/magento2-replace-all:dev-magento-2.3.4**, after composer install (removing everything from vendor/ first), I got:

```
  Problem 1
    - don't install yireo/magento2-replace-graphql 2.3.4|don't install yireo/magento2-replace-core 2.3.4
    - yireo/magento2-replace-all dev-magento-2.3.4 requires yireo/magento2-replace-core 2.3.4 -> satisfiable by yireo/magento2-replace-core[2.3.4].
    - yireo/magento2-replace-all dev-magento-2.3.4 requires yireo/magento2-replace-graphql 2.3.4 -> satisfiable by yireo/magento2-replace-graphql[2.3.4].
    - Installation request for yireo/magento2-replace-all dev-magento-2.3.4 -> satisfiable by yireo/magento2-replace-all[dev-magento-2.3.4].
```

**Comment by jissereitsma** [comment] 2020-04-30 11:00
Issue 1 is now fixed: The branches (like `magento-2.3.4`) are now released as proper releases (like `2.3.4`.

As for the second issue, it is quite an issue: https://github.com/yireo/magento2-replace-core/pull/3

I would like to raise another issue: Why are you replacing all (!) modules? Is this for testing or have you fully confirmed to yourself that none of these packages are needed?

Please note that this replacement is not meant to be a non-developer solution to downsize Magento. Instead, it is meant to help developers to come to the right solution. Any `replace` can be copied to your own `composer.json` file so that you can remove that thing you need to remove.

I'm closing this issue, because it is a duplicate of https://github.com/yireo/magento2-replace-core/pull/3

**Closed by jissereitsma** 2020-04-30 11:00 UTC
