### ISSUE TITLE
Error on 2.3.2

### ISSUE THREAD

**Issue by allrude** [yireo/magento2-replace-all#2] opened 2019-07-15 05:44 UTC
On a clean install of Magento 2.3.2 i get a error on;

`composer require yireo/magento2-replace-all:2.3.2`

Your requirements could not be resolved to an installable set of packages

running `composer require yireo/magento2-replace-all:2.3.1` on the same clean install works but ...

running setup:upgrade after that give's us this nice error;

`Class Magento\InventoryReservationsApi\Model\AppendReservationsInterface does not exist

In ClassReader.php line 35:`

**Comment by hanhpv** [comment] 2019-08-03 11:02
Have same issue

**Comment by LaurensGoedel** [comment] 2019-10-01 07:59
Same version, different error:
```
-bash-4.2$ composer require yireo/magento2-replace-all:2.3.2
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - don't install yireo/magento2-replace-graphql 2.3.2|don't install yireo/magento2-replace-core 2.3.2
    - yireo/magento2-replace-all 2.3.2 requires yireo/magento2-replace-core 2.3.2 -> satisfiable by yireo/magento2-replace-core[2.3.2].
    - yireo/magento2-replace-all 2.3.2 requires yireo/magento2-replace-graphql 2.3.2 -> satisfiable by yireo/magento2-replace-graphql[2.3.2].
    - Installation request for yireo/magento2-replace-all 2.3.2 -> satisfiable by yireo/magento2-replace-all[2.3.2].


Installation failed, reverting ./composer.json to its original content.

```

**Comment by jissereitsma** [comment] 2019-10-01 08:17
Could you try this? `composer require yireo/magento2-replace-all:2.3.2 --no-update`. Next, remove all `vendor` contents and run `composer install`.

**Comment by n0kit31** [comment] 2019-10-07 08:40
Hi @jissereitsma 
I think that your solution, which works indeed, is only a workaround.
Next time you will hit composer update there is still requirements issue:

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - don't install yireo/magento2-replace-graphql 2.3.2|don't install yireo/magento2-replace-core 2.3.2
    - yireo/magento2-replace-all 2.3.2 requires yireo/magento2-replace-core 2.3.2 -> satisfiable by yireo/magento2-replace-core[2.3.2].
    - yireo/magento2-replace-all 2.3.2 requires yireo/magento2-replace-graphql 2.3.2 -> satisfiable by yireo/magento2-replace-graphql[2.3.2].
    - Installation request for yireo/magento2-replace-all 2.3.2 -> satisfiable by yireo/magento2-replace-all[2.3.2].`

**Comment by nocturnalfrog** [comment] 2019-10-07 14:22
@jissereitsma,  

It looks lik @n0kit31  is right; there are some issues with this workaround.
I can confirm that it doesn't work on a fresh composer install for instance.

**Comment by nocturnalfrog** [comment] 2019-10-15 09:26
Hi @jissereitsma, 
Could you have a look at the [PR](https://github.com/yireo/magento2-replace-core/pull/3) and let me know what you think?

**Comment by jissereitsma** [comment] 2020-05-02 13:36
Closing because of new approach

**Closed by jissereitsma** 2020-05-02 13:36 UTC
